{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "95fb136d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import pickle\n",
    "\n",
    "# ── LOAD ARTIFACTS ────────────────────────────────────────\n",
    "with open(\"model.pkl\", \"rb\") as f:\n",
    "    model = pickle.load(f)\n",
    "with open(\"scaler.pkl\", \"rb\") as f:\n",
    "    scaler = pickle.load(f)\n",
    "with open(\"feature_columns.pkl\", \"rb\") as f:\n",
    "    feature_columns = pickle.load(f)\n",
    "\n",
    "# ── RISK CATEGORISATION (from predict_proba) ──────────────\n",
    "def categorise_risk(probability):\n",
    "    if probability < 0.35:\n",
    "        return \"🟢 Low Risk\", \"green\", probability\n",
    "    elif probability < 0.65:\n",
    "        return \"🟡 Moderate Risk\", \"orange\", probability\n",
    "    else:\n",
    "        return \"🔴 High Risk\", \"red\", probability\n",
    "\n",
    "# ── FEATURE ENGINEERING (mirrors your notebook exactly) ───\n",
    "def engineer_features(input_dict):\n",
    "    df = pd.DataFrame([input_dict])\n",
    "\n",
    "    # BMI category\n",
    "    def bmi_category(bmi):\n",
    "        if bmi < 18.5:       return \"Underweight\"\n",
    "        elif bmi <= 24.9:    return \"Normal\"\n",
    "        elif bmi <= 29.9:    return \"Overweight\"\n",
    "        elif bmi <= 34.9:    return \"Obesity 1\"\n",
    "        elif bmi <= 39.9:    return \"Obesity 2\"\n",
    "        else:                return \"Obesity 3\"\n",
    "\n",
    "    df[\"NewBMI\"] = df[\"BMI\"].apply(bmi_category)\n",
    "\n",
    "    # Glucose category\n",
    "    df[\"New_Glucose\"] = pd.cut(\n",
    "        df[\"Glucose\"],\n",
    "        bins=[0, 74, 99, 139, 200],\n",
    "        labels=[\"Low\", \"Normal\", \"Overweight\", \"High\"]\n",
    "    )\n",
    "    df[\"New_Glucose\"] = df[\"New_Glucose\"].astype(str)\n",
    "\n",
    "    # Insulin score\n",
    "    df[\"NewInsulinScore\"] = df[\"Insulin\"].apply(\n",
    "        lambda x: \"Normal\" if 16 <= x <= 166 else \"Abnormal\"\n",
    "    )\n",
    "\n",
    "    # One-hot encode (drop_first=True, same as training)\n",
    "    categorical_columns = [\"NewBMI\", \"New_Glucose\", \"NewInsulinScore\"]\n",
    "    df = pd.get_dummies(df, columns=categorical_columns, drop_first=True)\n",
    "    df.columns = df.columns.str.replace(\" \", \"_\")\n",
    "\n",
    "    # Align to training columns — fill missing OHE columns with 0\n",
    "    for col in feature_columns:\n",
    "        if col not in df.columns:\n",
    "            df[col] = 0\n",
    "\n",
    "    return df[feature_columns]  # same column order as training\n",
    "\n",
    "# ── UI ────────────────────────────────────────────────────\n",
    "st.set_page_config(page_title=\"Diabetes Risk Predictor\", page_icon=\"🩺\")\n",
    "st.title(\"🩺 Diabetes Risk Predictor\")\n",
    "st.markdown(\"Enter the patient's medical details below to assess their diabetes risk.\")\n",
    "st.divider()\n",
    "\n",
    "col1, col2 = st.columns(2)\n",
    "\n",
    "with col1:\n",
    "    pregnancies     = st.number_input(\"Pregnancies\",         min_value=0,    max_value=20,   value=1)\n",
    "    glucose         = st.number_input(\"Glucose (mg/dL)\",     min_value=0,    max_value=300,  value=110)\n",
    "    blood_pressure  = st.number_input(\"Blood Pressure (mmHg)\", min_value=0,  max_value=200,  value=72)\n",
    "    skin_thickness  = st.number_input(\"Skin Thickness (mm)\", min_value=0,    max_value=100,  value=20)\n",
    "\n",
    "with col2:\n",
    "    insulin         = st.number_input(\"Insulin (mu U/ml)\",   min_value=0,    max_value=900,  value=80)\n",
    "    bmi             = st.number_input(\"BMI\",                 min_value=0.0,  max_value=70.0, value=25.0, format=\"%.1f\")\n",
    "    dpf             = st.number_input(\"Diabetes Pedigree Function\", min_value=0.0, max_value=3.0, value=0.5, format=\"%.3f\")\n",
    "    age             = st.number_input(\"Age\",                 min_value=21,   max_value=120,  value=30)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "if st.button(\"🔍 Predict Risk\", use_container_width=True):\n",
    "\n",
    "    input_dict = {\n",
    "        \"Pregnancies\": pregnancies,\n",
    "        \"Glucose\": glucose,\n",
    "        \"BloodPressure\": blood_pressure,\n",
    "        \"SkinThickness\": skin_thickness,\n",
    "        \"Insulin\": insulin,\n",
    "        \"BMI\": bmi,\n",
    "        \"DiabetesPedigreeFunction\": dpf,\n",
    "        \"Age\": age\n",
    "    }\n",
    "\n",
    "    # Pipeline: engineer → scale → predict\n",
    "    X_input = engineer_features(input_dict)\n",
    "    X_scaled = scaler.transform(X_input)\n",
    "    probability = model.predict_proba(X_scaled)[0][1]  # prob of diabetes\n",
    "\n",
    "    label, colour, prob = categorise_risk(probability)\n",
    "\n",
    "    # ── RESULTS ───────────────────────────────────────────\n",
    "    st.subheader(\"Result\")\n",
    "    st.markdown(f\"### {label}\", unsafe_allow_html=False)\n",
    "    st.progress(float(probability))\n",
    "    st.metric(\"Diabetes Probability\", f\"{probability:.1%}\")\n",
    "\n",
    "    if colour == \"green\":\n",
    "        st.success(\"Low probability of diabetes. Maintain a healthy lifestyle.\")\n",
    "    elif colour == \"orange\":\n",
    "        st.warning(\"Moderate risk detected. Consider consulting a healthcare professional.\")\n",
    "    else:\n",
    "        st.error(\"High risk detected. Please seek medical advice promptly.\")\n",
    "\n",
    "    with st.expander(\"📊 Probability Breakdown\"):\n",
    "        st.write(f\"- **Low Risk threshold** : < 35% → Your score: `{probability:.1%}`\")\n",
    "        st.write(f\"- **Moderate Risk threshold** : 35% – 65% → Your score: `{probability:.1%}`\")\n",
    "        st.write(f\"- **High Risk threshold** : > 65% → Your score: `{probability:.1%}`\")\n",
    "\n",
    "    st.caption(\"⚠️ This tool is for informational purposes only and is not a clinical diagnosis.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
